# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listePersonnes = QtWidgets.QScrollArea(self.centralwidget)
        self.listePersonnes.setGeometry(QtCore.QRect(570, 10, 221, 511))
        self.listePersonnes.setWidgetResizable(True)
        self.listePersonnes.setObjectName("listePersonnes")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(200, 0, 16, 511))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.listePersonnes.setWidget(self.scrollAreaWidgetContents)
        self.removeCarButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeCarButton.setGeometry(QtCore.QRect(10, 530, 271, 23))
        self.removeCarButton.setObjectName("removeCarButton")
        self.addCarButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCarButton.setGeometry(QtCore.QRect(290, 530, 271, 23))
        self.addCarButton.setObjectName("addCarButton")
        self.AddPersonneButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddPersonneButton.setGeometry(QtCore.QRect(570, 530, 221, 23))
        self.AddPersonneButton.setObjectName("AddPersonneButton")
        self.meteoBox = QtWidgets.QGroupBox(self.centralwidget)
        self.meteoBox.setGeometry(QtCore.QRect(10, 10, 551, 121))
        self.meteoBox.setObjectName("meteoBox")
        self.carsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.carsBox.setGeometry(QtCore.QRect(10, 140, 551, 381))
        self.carsBox.setObjectName("carsBox")
        self.carsScrollArea = QtWidgets.QScrollArea(self.carsBox)
        self.carsScrollArea.setGeometry(QtCore.QRect(10, 20, 531, 351))
        self.carsScrollArea.setWidgetResizable(True)
        self.carsScrollArea.setObjectName("carsScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 529, 349))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(510, 0, 20, 351))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 491, 80))
        self.widget.setObjectName("widget")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 471, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.ratioLCD = QtWidgets.QLCDNumber(self.widget)
        self.ratioLCD.setGeometry(QtCore.QRect(433, 20, 51, 23))
        self.ratioLCD.setObjectName("ratioLCD")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(170, 30, 111, 16))
        self.label_4.setObjectName("label_4")
        self.carsScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.removeCarButton.setText(_translate("MainWindow", "Retirer un car"))
        self.addCarButton.setText(_translate("MainWindow", "Ajouter un car"))
        self.AddPersonneButton.setText(_translate("MainWindow", "Ajouter une personne"))
        self.meteoBox.setTitle(_translate("MainWindow", "Météo"))
        self.carsBox.setTitle(_translate("MainWindow", "Cars"))
        self.label.setText(_translate("MainWindow", "Car 1"))
        self.label_2.setText(_translate("MainWindow", "Ratio eleves / prof"))
        self.label_3.setText(_translate("MainWindow", "Nombre d\'élèves : 5"))
        self.label_4.setText(_translate("MainWindow", "Nombre profs : 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
